import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";


const myFont = localFont({
    src: "./fonts/kindergarten.ttf",
    variable: "--font-custom",
});

const secondFont = localFont({
    src: "./fonts/ADELIA.otf",
    variable: "--font-adelia",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${myFont.variable} ${secondFont.variable} ${lexend.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {children}
      </body>
      </html>
  );
}
